long_fq_root:
    "path/to/long/reads"
short_fq_root:
    "path/to/short/reads"
dehumanizer_database_root:
    "path/to/dh/refs"
kraken2_database_root:
    "path/to/kraken/db"
genome_size:
    "100m"
slack_token:
    ""
slack_channel:
    "#general"
cuda:
    False
medaka_env:
    "path/to/singularity/container"
