channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.8.1
  - python =3.6
  - networkx =2.1
  - matplotlib =2.2.3
  - bcftools =1.9
  - samtools =1.9
  - pysam =0.15.0
  - pyvcf
  - pandas
  - biopython
  - minimap2
  - racon
  - seqtk
  - kraken2
  - seqkit
  - datamash
  - pip:
    - git+https://github.com/SamStudio8/bondage.git
    - git+https://github.com/SamStudio8/dehumanizer.git
    - git+https://github.com/SamStudio8/ktkit.git
    - slackclient==1.3.1
    - GPUtil
